[versions]
org-jetbrains-kotlin = "2.3.0"

[libraries]
com-fasterxml-jackson-core-jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.21.0"
com-zegreatrob-testmints-testmints-bom = "com.zegreatrob.testmints:testmints-bom:12.5.27"
nl-littlerobots-vcu-plugin = "nl.littlerobots.vcu:plugin:1.0.1"
org-apache-logging-log4j-log4j-core = "org.apache.logging.log4j:log4j-core:2.25.3"
org-jetbrains-kotlin-kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-plugin-js-plain-objects = { module = "org.jetbrains.kotlin.plugin.js-plain-objects:org.jetbrains.kotlin.plugin.js-plain-objects.gradle.plugin", version.ref = "org-jetbrains-kotlin" }
org-jmailen-gradle-kotlinter-gradle = "org.jmailen.gradle:kotlinter-gradle:5.3.0"

[plugins]
nl-littlerobots-version-catalog-update = "nl.littlerobots.version-catalog-update:1.0.1"
org-jetbrains-kotlin-plugin-js-plain-objects = "org.jetbrains.kotlin.plugin.js-plain-objects:2.3.0"
org-jmailen-kotlinter = "org.jmailen.kotlinter:5.3.0"
