[plugins]
com-github-sghill-distribution-sha = "com.github.sghill.distribution-sha:0.4.0"
com-zegreatrob-tools-digger = "com.zegreatrob.tools.digger:1.7.8"
com-zegreatrob-tools-tagger = "com.zegreatrob.tools.tagger:1.7.8"
nl-littlerobots-version-catalog-update = "nl.littlerobots.version-catalog-update:1.0.0"
